language: go
sudo: required
services:
- docker
addons:
  apt:
    packages:
    - docker-ce
script:
- "./travis-build.sh"
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: WWC2hZsX17+6kQ10lZFtdqd1XUeTNaSOvORMFvHJmz85HGghbNadYjgCEBzyRSWjeXLqrPgl3ZNb/Zv3N7uIN7UZ3Et3zkWM7O+crmhLqNvmTmJviUoHZhtrAU+kwQipx/wFlpNmOI2EQnzz6LK5jQ7Gt4JBS29WRViPSRvaYMYUiGh+eBpAZSMGLLauFBSr1VjgixwVWCYME1oHn7dBbiVgsM679xfyttgKDo1LJjnj+OtNJNhSM/eK1WprsdKPlFFomSZlrRgyd6neoxXfWPttkww7J/ZyynFfB8CbCDdYOto95SQosYgpq0HEeLF9pCHS8rIXffc456Kg67lPHJKv3850PvPx+XcO93z5qtDmktnj1PdopZqZzZMNxk09lxzhD3+fZMjOP9/N5zR1AXQ9o5ZStExLQK/YHyYOjfrVqz3I3KPLHo5SR65I9bXzzKMwrT3fdRFDDzUqyGDvgJqrxti3+WfWVys6KJOF1nAVQHPpwQ3VY38QzSHTlh58On3YRGStcLaWcO6u7MDHz2a/Z7HycfgihMXXOt+GV9Wwh159Wg+FvhdS9jYzX5XA/AuOOOXH88nGFL/9+ZRGpHhtWJdHYICY7//reQDrKXf8lx8jacpWeMm8ohyesw15V6TCxMJJ7oYzFRwCBE8rruKvkHFaSJW1FsPS429m3PA=
  - secure: ebTMXg/fTYQXoExJJv32quQJQyP2nKN53bS4vbNLvvEfW28IftnAtLN94G5Mg30m7+8qK8h9XMRIAfGTBmFleVnZxBAjj6bA9BTf/Tdo6UYbq/RLzJZtoZ8t+sYLUbK4dTxz+IZ/7cpLFMV0EtHlkVZd+x3YtO6p0hb6AdCRbFy9NvRWsLO4FBRzlPrOdtZ/ppwHRWpCFPzpgdczxhkBtPUgefyCFv1goF5/TyxQIOKqF8kZ0AjpAJ7XMHP1OCvbcaDrHy1oVNJm+ZiMSmBPNiDWkXH2Tv8RO7a0Cy5LYlA5ABGMQMT8Hd17J9r8ozennfygbbSRrUGwn8HVps1mZoa7AgJkwbGXP1PrU+DeZncQJ2oMdfgwRwmAdLDMD+4ir9scL79AlEpdB7bKqb9cgqqiVIbV0bXJSGjlXrnO9JcBtUINHJYPV3s+3EgmX4wPraedKgBupxMpv57xHj5vokf4OsRXdtEH08kEu4g0QNzu0T8EGIDBMX9rLoAibQrQ6VJb7Bdzv0cwHn5CVAuhjxHifAEsi8mVDUx4i3oaq9xwn2/5GaT80NyuqSLywGV227JvVgd8sWrH/0gJ1X4TQzlamKVfV7H4tmbTDS/0MAnoxyvcF4VprM5ciYESmPCuXM1JZQaY3kKPpHv660xDZx4VmtF6uhdXhrVGR6C/fLM=
